name: depesca
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  intl: ^0.20.2
  postgres: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/fondo.png
    - assets/images/m1.png
    - assets/images/m2.png
    - assets/images/m3.png
    - assets/images/m4.png
